<?php
return array (
  'pername' => 
  array (
    'fieldid' => '317',
    'modelid' => '21',
    'siteid' => '4',
    'field' => 'pername',
    'name' => '姓名',
    'tips' => '',
    'css' => 'placeholder="请输入姓名"',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'mobile' => 
  array (
    'fieldid' => '318',
    'modelid' => '21',
    'siteid' => '4',
    'field' => 'mobile',
    'name' => '联系电话',
    'tips' => '请输入您的联系电话',
    'css' => 'placeholder="请输入联系方式"',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '/^(1)[0-9]{10}$/',
    'errortips' => '请输入手机号码',
    'formtype' => 'text',
    'setting' => '{"size":"","defaultvalue":"","ispassword":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'pcalled' => 
  array (
    'fieldid' => '319',
    'modelid' => '21',
    'siteid' => '4',
    'field' => 'pcalled',
    'name' => '称呼',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 'array (
  \'options\' => \'先生|1
女士|2\',
  \'boxtype\' => \'radio\',
  \'fieldtype\' => \'varchar\',
  \'minnumber\' => \'1\',
  \'cols\' => \'5\',
  \'width\' => \'80\',
  \'size\' => \'1\',
  \'defaultvalue\' => \'\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '先生|1
女士|2',
    'boxtype' => 'radio',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'cols' => '5',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '',
  ),
  'pmail' => 
  array (
    'fieldid' => '321',
    'modelid' => '21',
    'siteid' => '4',
    'field' => 'pmail',
    'name' => '邮箱',
    'tips' => '请输入您的邮箱地址',
    'css' => 'placeholder="请输入您的邮箱"',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 'array (
  \'size\' => \'49\',
  \'defaultvalue\' => \'\',
  \'ispassword\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'size' => '49',
    'defaultvalue' => '',
    'ispassword' => '0',
  ),
  'pneed' => 
  array (
    'fieldid' => '322',
    'modelid' => '21',
    'siteid' => '4',
    'field' => 'pneed',
    'name' => '需求',
    'tips' => '',
    'css' => 'placeholder="请输入您的需求详情"',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'textarea',
    'setting' => '{"width":"79","height":"100","defaultvalue":"","enablehtml":"0"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'width' => '79',
    'height' => '100',
    'defaultvalue' => '',
    'enablehtml' => '0',
  ),
  'pversion' => 
  array (
    'fieldid' => '506',
    'modelid' => '21',
    'siteid' => '4',
    'field' => 'pversion',
    'name' => '产品版本',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => '{"options":"\\u4e2d\\u5c0f\\u5b66\\u57f9\\u8bad|1\\r\\n\\u7559\\u5b66\\u57f9\\u8bad|2\\r\\n\\u5916\\u8bed\\u57f9\\u8bad|3\\r\\n\\u5c11\\u513f\\u57f9\\u8bad|4\\r\\n\\u804c\\u4e1a\\u8d44\\u683c\\u57f9\\u8bad|5\\r\\n\\u827a\\u672f\\u57f9\\u8bad|6","boxtype":"select","fieldtype":"varchar","minnumber":"1","cols":"5","width":"80","size":"1","defaultvalue":"1"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '中小学培训|1
留学培训|2
外语培训|3
少儿培训|4
职业资格培训|5
艺术培训|6',
    'boxtype' => 'select',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'cols' => '5',
    'width' => '80',
    'size' => '1',
    'defaultvalue' => '1',
  ),
  'pscale' => 
  array (
    'fieldid' => '509',
    'modelid' => '21',
    'siteid' => '4',
    'field' => 'pscale',
    'name' => '机构规模',
    'tips' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => '{"options":"200\\u4eba\\u4ee5\\u5185|1\\r\\n200-500\\u4eba|2\\r\\n500-1000\\u4eba|3\\r\\n1000-3000\\u4eba|4\\r\\n3000-5000\\u4eba|5\\r\\n5000\\u4eba\\u4ee5\\u4e0a|6","boxtype":"radio","fieldtype":"varchar","minnumber":"1","cols":"2","width":"130","size":"1","defaultvalue":""}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '200人以内|1
200-500人|2
500-1000人|3
1000-3000人|4
3000-5000人|5
5000人以上|6',
    'boxtype' => 'radio',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'cols' => '2',
    'width' => '130',
    'size' => '1',
    'defaultvalue' => '',
  ),
  'remarks' => 
  array (
    'fieldid' => '503',
    'modelid' => '21',
    'siteid' => '4',
    'field' => 'remarks',
    'name' => '备注',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'textarea',
    'setting' => 'array (
  \'width\' => \'100%\',
  \'height\' => \'46\',
  \'defaultvalue\' => \'\',
  \'enablehtml\' => \'0\',
)',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '0',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '1',
    'disabled' => '0',
    'isomnipotent' => '0',
    'width' => '100%',
    'height' => '46',
    'defaultvalue' => '',
    'enablehtml' => '0',
  ),
);
?>