<?php
return array (
  10 => 
  array (
    'posid' => '10',
    'modelid' => '0',
    'catid' => '0',
    'name' => '栏目首页推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  27 => 
  array (
    'posid' => '27',
    'modelid' => '17',
    'catid' => '0',
    'name' => '首页资讯推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '4',
    'thumb' => '',
  ),
  26 => 
  array (
    'posid' => '26',
    'modelid' => '23',
    'catid' => '0',
    'name' => '首页资讯推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '3',
    'thumb' => '',
  ),
  25 => 
  array (
    'posid' => '25',
    'modelid' => '18',
    'catid' => '0',
    'name' => '案例列表页推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '4',
    'thumb' => '',
  ),
  24 => 
  array (
    'posid' => '24',
    'modelid' => '29',
    'catid' => '0',
    'name' => '成功案例栏目首页推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '2',
    'thumb' => '',
  ),
  23 => 
  array (
    'posid' => '23',
    'modelid' => '13',
    'catid' => '0',
    'name' => '资讯栏目精品推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '2',
    'thumb' => '',
  ),
  22 => 
  array (
    'posid' => '22',
    'modelid' => '14',
    'catid' => '0',
    'name' => '服务栏目下成功案例推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '2',
    'thumb' => '',
  ),
  21 => 
  array (
    'posid' => '21',
    'modelid' => '1',
    'catid' => '10',
    'name' => 'CRM栏目首页热点新闻',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  20 => 
  array (
    'posid' => '20',
    'modelid' => '1',
    'catid' => '0',
    'name' => '专题推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  19 => 
  array (
    'posid' => '19',
    'modelid' => '1',
    'catid' => '11',
    'name' => '教务栏目首页热点新闻',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  18 => 
  array (
    'posid' => '18',
    'modelid' => '1',
    'catid' => '0',
    'name' => '首页资讯推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  12 => 
  array (
    'posid' => '12',
    'modelid' => '0',
    'catid' => '0',
    'name' => '首页图片推荐',
    'maxnum' => '20',
    'extention' => NULL,
    'listorder' => '0',
    'siteid' => '1',
    'thumb' => '',
  ),
  28 => 
  array (
    'posid' => '28',
    'modelid' => '13',
    'catid' => '0',
    'name' => '首页资讯推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '2',
    'thumb' => '',
  ),
);
?>