<?php
return array (
  1 => 
  array (
    'siteid' => '1',
    'name' => '可为时代官方网站',
    'dirname' => '',
    'domain' => 'http://www.keweisoft.com/',
    'site_title' => '可为时代官网 — 教育行业信息化解决方案引领者',
    'keywords' => '教育erp系统,教育培训机构一体化解决方案,教育培训信息化咨询商',
    'description' => '可为时代成立于1993年，多年来专注于教育行业信息化管理建设，具有丰富的教育行业信息化经验。可为开发的edus教育培训管理系统是针对教育培训行业研发的一体化的信息化教务管理系统，兼容传统教务管理系统、CRM和ERP的优势，结合国际最先进教育培训行业管理理念，打造全新（数字化）培训学校管理系统,帮助培训机构快速实现市场、销售、客户服务、教学、教务、财务一体化，多校区多部门的多中心管理等业务全面的信息化与一体化。',
    'release_point' => '',
    'default_style' => 'keweisoft',
    'template' => 'keweisoft',
    'setting' => '{"upload_maxsize":"2048","upload_allowext":"jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf","watermark_enable":"1","watermark_minwidth":"300","watermark_minheight":"300","watermark_img":"statics\\/images\\/water\\/\\/mark.png","watermark_pct":"85","watermark_quality":"80","watermark_pos":"9"}',
    'uuid' => '59cd4049-cdeb-11e4-9d29-e03f49825df2',
    'url' => 'http://www.keweisoft.com/',
  ),
  2 => 
  array (
    'siteid' => '2',
    'name' => '可为CRM',
    'dirname' => 'crm',
    'domain' => 'http://crm.keweisoft.com/',
    'site_title' => '教育培训CRM|培训CRM|教育CRM|教育行业CRM软件|培训学校客户管理系统 — 可为CRM，国内领先的教育培训CRM系统',
    'keywords' => '教育crm,教育培训crm,培训crm，教育行业crm软件,培训学校客户管理系统,培训机构客户管理系统',
    'description' => '可为教育培训CRM是教育培训行业内领先的客户关系管理软件，可为CRM为教育培训机构提供市场、销售、服务、教学、办公、财务等为主的一体化教育培训解决方案。同时支持个性化开发定制，为教育培训机构提供最专业、最全面的解决方案，拥有千余家行业成功案例和行业纵深经验丰富的服务团队。可为CRM免费咨询电话：010-51651266',
    'release_point' => '',
    'default_style' => 'crm',
    'template' => 'crm',
    'setting' => 'array (
  \'upload_maxsize\' => \'2000\',
  \'upload_allowext\' => \'jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf\',
  \'watermark_enable\' => \'0\',
  \'watermark_minwidth\' => \'300\',
  \'watermark_minheight\' => \'300\',
  \'watermark_img\' => \'statics/images/water/http://www.keweisoft.com/mark.gif\',
  \'watermark_pct\' => \'100\',
  \'watermark_quality\' => \'80\',
  \'watermark_pos\' => \'9\',
)',
    'uuid' => '',
    'url' => 'http://crm.keweisoft.com/',
  ),
  3 => 
  array (
    'siteid' => '3',
    'name' => '手机站',
    'dirname' => 'm',
    'domain' => 'http://m.keweisoft.com/',
    'site_title' => '可为时代科技有限公司',
    'keywords' => '',
    'description' => '',
    'release_point' => '',
    'default_style' => 'mobile',
    'template' => 'mobile',
    'setting' => 'array (
  \'upload_maxsize\' => \'2000\',
  \'upload_allowext\' => \'jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf\',
  \'watermark_enable\' => \'0\',
  \'watermark_minwidth\' => \'300\',
  \'watermark_minheight\' => \'300\',
  \'watermark_img\' => \'statics/images/water/http://www.keweisoft.com/mark.gif\',
  \'watermark_pct\' => \'100\',
  \'watermark_quality\' => \'80\',
  \'watermark_pos\' => \'9\',
)',
    'uuid' => '',
    'url' => 'http://m.keweisoft.com/',
  ),
  4 => 
  array (
    'siteid' => '4',
    'name' => '可为edus培训机构管理软件',
    'dirname' => 'edus',
    'domain' => 'http://edus.keweisoft.com/',
    'site_title' => '教育机构中心管理系统|培训学校管理软件 — 可为edus，专门针对培训机构的管理系统',
    'keywords' => '培训中心管理软件,教育机构管理系统,教育机构管理软件,培训学校管理系统,培训学校管理软件,培训机构管理系统,培训机构管理软件,培训中心管理系统',
    'description' => '可为edus教务系统是教育培训行业内领先的管理软件，为广大教育培训机构客户提供先进的管理思想和管理工具，为培训机构提供专业的信息化解决方案。',
    'release_point' => '',
    'default_style' => 'edus',
    'template' => 'edus',
    'setting' => '{"upload_maxsize":"2000","upload_allowext":"jpg|jpeg|gif|bmp|png|doc|docx|xls|xlsx|ppt|pptx|pdf|txt|rar|zip|swf","watermark_enable":"0","watermark_minwidth":"300","watermark_minheight":"300","watermark_img":"statics\\/images\\/water\\/http:\\/\\/www.keweisoft.com\\/mark.gif","watermark_pct":"100","watermark_quality":"80","watermark_pos":"9"}',
    'uuid' => '',
    'url' => 'http://edus.keweisoft.com/',
  ),
);
?>